# Generated by Django 5.2.6 on 2025-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_subjectdb_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdb',
            name='id',
        ),
        migrations.AddField(
            model_name='subjectdb',
            name='srno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
